name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%S)"

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DHNAME }}/DevOps-intern:${{ steps.timestamp.outputs.timestamp}} -f Dockerfile .
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DHNAME }}
          password: ${{ secrets.DHPASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DHNAME }}/DevOps-intern:${{ steps.timestamp.outputs.timestamp}}
        
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
          
      - name: Fetch the update the latest image tag
        id: get-latest-tag
        run: |
          repository="hussain2844/DevOps-intern"
          tags_info=$(curl -s "https://registry.hub.docker.com/v2/repositories/$repository/tags/" | jq -r '.results[] | "\(.name) \(.last_updated)"')
          sorted_tags_info=$(echo "$tags_info" | sort -k2)
          latest_tag_info=$(echo "$sorted_tags_info" | tail -n 1)
          latest_tag=$(echo "$latest_tag_info" | awk '{print $1}')
          sed -i "s|tag:.*|tag: $latest_tag|" helm-webapp/values.yaml
        shell: bash
    
      - name: Commit and push Deployment changes
        run: |
          git config --global user.email "${{ secrets.MAIL }}"
          git config --global user.name "mdhussain28"
      
          git add helm-webapp/values.yaml
          git commit -m "Update image tag to $latest_tag"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
